/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_copyleftgames_playerd_bluetooth_Helper_DeviceReceiver */

#ifndef _Included_org_copyleftgames_playerd_bluetooth_Helper_DeviceReceiver
#define _Included_org_copyleftgames_playerd_bluetooth_Helper_DeviceReceiver
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
